# Generated by Django 4.2.1 on 2023-06-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_songs', to='tunaapi.artist'),
        ),
        migrations.AlterField(
            model_name='songgenre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunaapi.genre'),
        ),
        migrations.AlterField(
            model_name='songgenre',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='tunaapi.song'),
        ),
    ]
